# Generated by Django 4.1.5 on 2023-01-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('buyitem', 'buyitem'), ('cancel', 'canel'), ('intransit', 'intransit'), ('orderplaced', 'orderplaced')], default='buyitem', max_length=30),
        ),
    ]
